# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml
#

name: first workflow
on: push
jobs:
  build: # job 이름
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello World"

      - name: Checkout code
        uses: actions/checkout@v4 # actions -> 재사용 가능한 작업

      - name: install deps
        run: npm ci # ci -> clean install -> package-lock.json
